[project]
name = "langgraph-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Saurav Anand", email = "sauravanand1608@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "groq>=1.7.0",
    "langgraph>=1.2.11",
    "python-dotenv>=1.2.3",
]

[project.scripts]
langgraph = "langgraph:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
[tool.uv]
package = false
